import type { Method } from "@/shared/bindings/bindings";

export type City = {
  id: string;
  name: string;
  country: string;
  latitude: number;
  longitude: number;
  timezone: string;
  method: Method;
};

export const cities: City[] = [
  {
    id: "karachi",
    name: "Karachi",
    country: "Pakistan",
    latitude: 24.8607,
    longitude: 67.0011,
    timezone: "Asia/Karachi",
    method: "karachi",
  },
  {
    id: "lahore",
    name: "Lahore",
    country: "Pakistan",
    latitude: 31.5204,
    longitude: 74.3587,
    timezone: "Asia/Karachi",
    method: "karachi",
  },
  {
    id: "islamabad",
    name: "Islamabad",
    country: "Pakistan",
    latitude: 33.6844,
    longitude: 73.0479,
    timezone: "Asia/Karachi",
    method: "karachi",
  },
  {
    id: "rawalpindi",
    name: "Rawalpindi",
    country: "Pakistan",
    latitude: 33.5651,
    longitude: 73.0169,
    timezone: "Asia/Karachi",
    method: "karachi",
  },
  {
    id: "faisalabad",
    name: "Faisalabad",
    country: "Pakistan",
    latitude: 31.4504,
    longitude: 73.135,
    timezone: "Asia/Karachi",
    method: "karachi",
  },
  {
    id: "multan",
    name: "Multan",
    country: "Pakistan",
    latitude: 30.1575,
    longitude: 71.5249,
    timezone: "Asia/Karachi",
    method: "karachi",
  },
  {
    id: "peshawar",
    name: "Peshawar",
    country: "Pakistan",
    latitude: 34.0151,
    longitude: 71.5249,
    timezone: "Asia/Karachi",
    method: "karachi",
  },
  {
    id: "quetta",
    name: "Quetta",
    country: "Pakistan",
    latitude: 30.1798,
    longitude: 66.975,
    timezone: "Asia/Karachi",
    method: "karachi",
  },
  {
    id: "hyderabad-pk",
    name: "Hyderabad",
    country: "Pakistan",
    latitude: 25.396,
    longitude: 68.3578,
    timezone: "Asia/Karachi",
    method: "karachi",
  },
  {
    id: "kabul",
    name: "Kabul",
    country: "Afghanistan",
    latitude: 34.5553,
    longitude: 69.2075,
    timezone: "Asia/Kabul",
    method: "karachi",
  },
  {
    id: "delhi",
    name: "Delhi",
    country: "India",
    latitude: 28.6139,
    longitude: 77.209,
    timezone: "Asia/Kolkata",
    method: "karachi",
  },
  {
    id: "mumbai",
    name: "Mumbai",
    country: "India",
    latitude: 19.076,
    longitude: 72.8777,
    timezone: "Asia/Kolkata",
    method: "karachi",
  },
  {
    id: "hyderabad-in",
    name: "Hyderabad",
    country: "India",
    latitude: 17.385,
    longitude: 78.4867,
    timezone: "Asia/Kolkata",
    method: "karachi",
  },
  {
    id: "bengaluru",
    name: "Bengaluru",
    country: "India",
    latitude: 12.9716,
    longitude: 77.5946,
    timezone: "Asia/Kolkata",
    method: "karachi",
  },
  {
    id: "dhaka",
    name: "Dhaka",
    country: "Bangladesh",
    latitude: 23.8103,
    longitude: 90.4125,
    timezone: "Asia/Dhaka",
    method: "karachi",
  },
  {
    id: "dubai",
    name: "Dubai",
    country: "UAE",
    latitude: 25.2048,
    longitude: 55.2708,
    timezone: "Asia/Dubai",
    method: "dubai",
  },
  {
    id: "abu-dhabi",
    name: "Abu Dhabi",
    country: "UAE",
    latitude: 24.4539,
    longitude: 54.3773,
    timezone: "Asia/Dubai",
    method: "dubai",
  },
  {
    id: "sharjah",
    name: "Sharjah",
    country: "UAE",
    latitude: 25.3463,
    longitude: 55.4209,
    timezone: "Asia/Dubai",
    method: "dubai",
  },
  {
    id: "riyadh",
    name: "Riyadh",
    country: "Saudi Arabia",
    latitude: 24.7136,
    longitude: 46.6753,
    timezone: "Asia/Riyadh",
    method: "ummAlQura",
  },
  {
    id: "jeddah",
    name: "Jeddah",
    country: "Saudi Arabia",
    latitude: 21.4858,
    longitude: 39.1925,
    timezone: "Asia/Riyadh",
    method: "ummAlQura",
  },
  {
    id: "makkah",
    name: "Makkah",
    country: "Saudi Arabia",
    latitude: 21.4225,
    longitude: 39.8262,
    timezone: "Asia/Riyadh",
    method: "ummAlQura",
  },
  {
    id: "madinah",
    name: "Madinah",
    country: "Saudi Arabia",
    latitude: 24.5247,
    longitude: 39.5692,
    timezone: "Asia/Riyadh",
    method: "ummAlQura",
  },
  {
    id: "doha",
    name: "Doha",
    country: "Qatar",
    latitude: 25.2854,
    longitude: 51.531,
    timezone: "Asia/Qatar",
    method: "qatar",
  },
  {
    id: "kuwait-city",
    name: "Kuwait City",
    country: "Kuwait",
    latitude: 29.3759,
    longitude: 47.9774,
    timezone: "Asia/Kuwait",
    method: "kuwait",
  },
  {
    id: "manama",
    name: "Manama",
    country: "Bahrain",
    latitude: 26.2285,
    longitude: 50.586,
    timezone: "Asia/Bahrain",
    method: "ummAlQura",
  },
  {
    id: "muscat",
    name: "Muscat",
    country: "Oman",
    latitude: 23.588,
    longitude: 58.3829,
    timezone: "Asia/Muscat",
    method: "ummAlQura",
  },
  {
    id: "cairo",
    name: "Cairo",
    country: "Egypt",
    latitude: 30.0444,
    longitude: 31.2357,
    timezone: "Africa/Cairo",
    method: "egyptian",
  },
  {
    id: "istanbul",
    name: "Istanbul",
    country: "Turkey",
    latitude: 41.0082,
    longitude: 28.9784,
    timezone: "Europe/Istanbul",
    method: "muslimWorldLeague",
  },
  {
    id: "amman",
    name: "Amman",
    country: "Jordan",
    latitude: 31.9454,
    longitude: 35.9284,
    timezone: "Asia/Amman",
    method: "muslimWorldLeague",
  },
  {
    id: "casablanca",
    name: "Casablanca",
    country: "Morocco",
    latitude: 33.5731,
    longitude: -7.5898,
    timezone: "Africa/Casablanca",
    method: "muslimWorldLeague",
  },
  {
    id: "lagos",
    name: "Lagos",
    country: "Nigeria",
    latitude: 6.5244,
    longitude: 3.3792,
    timezone: "Africa/Lagos",
    method: "muslimWorldLeague",
  },
  {
    id: "nairobi",
    name: "Nairobi",
    country: "Kenya",
    latitude: -1.2921,
    longitude: 36.8219,
    timezone: "Africa/Nairobi",
    method: "muslimWorldLeague",
  },
  {
    id: "johannesburg",
    name: "Johannesburg",
    country: "South Africa",
    latitude: -26.2041,
    longitude: 28.0473,
    timezone: "Africa/Johannesburg",
    method: "muslimWorldLeague",
  },
  {
    id: "kuala-lumpur",
    name: "Kuala Lumpur",
    country: "Malaysia",
    latitude: 3.139,
    longitude: 101.6869,
    timezone: "Asia/Kuala_Lumpur",
    method: "muslimWorldLeague",
  },
  {
    id: "jakarta",
    name: "Jakarta",
    country: "Indonesia",
    latitude: -6.2088,
    longitude: 106.8456,
    timezone: "Asia/Jakarta",
    method: "muslimWorldLeague",
  },
  {
    id: "singapore",
    name: "Singapore",
    country: "Singapore",
    latitude: 1.3521,
    longitude: 103.8198,
    timezone: "Asia/Singapore",
    method: "muslimWorldLeague",
  },
  {
    id: "london",
    name: "London",
    country: "United Kingdom",
    latitude: 51.5074,
    longitude: -0.1278,
    timezone: "Europe/London",
    method: "muslimWorldLeague",
  },
  {
    id: "birmingham",
    name: "Birmingham",
    country: "United Kingdom",
    latitude: 52.4862,
    longitude: -1.8904,
    timezone: "Europe/London",
    method: "muslimWorldLeague",
  },
  {
    id: "manchester",
    name: "Manchester",
    country: "United Kingdom",
    latitude: 53.4808,
    longitude: -2.2426,
    timezone: "Europe/London",
    method: "muslimWorldLeague",
  },
  {
    id: "paris",
    name: "Paris",
    country: "France",
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: "Europe/Paris",
    method: "muslimWorldLeague",
  },
  {
    id: "berlin",
    name: "Berlin",
    country: "Germany",
    latitude: 52.52,
    longitude: 13.405,
    timezone: "Europe/Berlin",
    method: "muslimWorldLeague",
  },
  {
    id: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    latitude: 52.3676,
    longitude: 4.9041,
    timezone: "Europe/Amsterdam",
    method: "muslimWorldLeague",
  },
  {
    id: "stockholm",
    name: "Stockholm",
    country: "Sweden",
    latitude: 59.3293,
    longitude: 18.0686,
    timezone: "Europe/Stockholm",
    method: "muslimWorldLeague",
  },
  {
    id: "toronto",
    name: "Toronto",
    country: "Canada",
    latitude: 43.6532,
    longitude: -79.3832,
    timezone: "America/Toronto",
    method: "northAmerica",
  },
  {
    id: "vancouver",
    name: "Vancouver",
    country: "Canada",
    latitude: 49.2827,
    longitude: -123.1207,
    timezone: "America/Vancouver",
    method: "northAmerica",
  },
  {
    id: "new-york",
    name: "New York",
    country: "United States",
    latitude: 40.7128,
    longitude: -74.006,
    timezone: "America/New_York",
    method: "northAmerica",
  },
  {
    id: "chicago",
    name: "Chicago",
    country: "United States",
    latitude: 41.8781,
    longitude: -87.6298,
    timezone: "America/Chicago",
    method: "northAmerica",
  },
  {
    id: "houston",
    name: "Houston",
    country: "United States",
    latitude: 29.7604,
    longitude: -95.3698,
    timezone: "America/Chicago",
    method: "northAmerica",
  },
  {
    id: "los-angeles",
    name: "Los Angeles",
    country: "United States",
    latitude: 34.0522,
    longitude: -118.2437,
    timezone: "America/Los_Angeles",
    method: "northAmerica",
  },
  {
    id: "sydney",
    name: "Sydney",
    country: "Australia",
    latitude: -33.8688,
    longitude: 151.2093,
    timezone: "Australia/Sydney",
    method: "muslimWorldLeague",
  },
  {
    id: "melbourne",
    name: "Melbourne",
    country: "Australia",
    latitude: -37.8136,
    longitude: 144.9631,
    timezone: "Australia/Melbourne",
    method: "muslimWorldLeague",
  },
];

export function cityById(id: string): City | undefined {
  return cities.find((city) => city.id === id);
}
