// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getAppInfo: () => typedError<AppInfo, CommandError>(__TAURI_INVOKE("get_app_info")),
	setOverlayHitAreas: (rects: Rect[]) => typedError<null, CommandError>(__TAURI_INVOKE("set_overlay_hit_areas", { rects })),
	getOverlayState: () => typedError<OverlaySnapshot, CommandError>(__TAURI_INVOKE("get_overlay_state")),
	setOrbState: (state: OrbState) => typedError<null, CommandError>(__TAURI_INVOKE("set_orb_state", { state })),
	setFollowMode: (mode: FollowMode) => typedError<null, CommandError>(__TAURI_INVOKE("set_follow_mode", { mode })),
	setOrbProgress: (progress: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("set_orb_progress", { progress })),
	showBubble: (text: string, actions: BubbleAction[]) => typedError<number, CommandError>(__TAURI_INVOKE("show_bubble", { text, actions })),
	resolveBubble: (id: number, actionId: string | null) => typedError<null, CommandError>(__TAURI_INVOKE("resolve_bubble", { id, actionId })),
	setPanelOpen: (open: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_panel_open", { open })),
	listTasks: (filter: TaskFilter) => typedError<Task[], CommandError>(__TAURI_INVOKE("list_tasks", { filter })),
	createTask: (input: TaskInput) => typedError<Task, CommandError>(__TAURI_INVOKE("create_task", { input })),
	updateTask: (id: number, input: TaskInput) => typedError<Task, CommandError>(__TAURI_INVOKE("update_task", { id, input })),
	setTaskStatus: (id: number, status: TaskStatus) => typedError<Task, CommandError>(__TAURI_INVOKE("set_task_status", { id, status })),
	setTaskTopThree: (id: number, on: boolean) => typedError<Task, CommandError>(__TAURI_INVOKE("set_task_top_three", { id, on })),
	deleteTask: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("delete_task", { id })),
	listCategories: () => typedError<Category[], CommandError>(__TAURI_INVOKE("list_categories")),
	createCategory: (input: CategoryInput) => typedError<Category, CommandError>(__TAURI_INVOKE("create_category", { input })),
	quickAddTask: (text: string) => typedError<QuickAddOutcome, CommandError>(__TAURI_INVOKE("quick_add_task", { text })),
	createReminder: (input: ReminderInput) => typedError<Reminder, CommandError>(__TAURI_INVOKE("create_reminder", { input })),
	listTaskReminders: (taskId: number) => typedError<Reminder[], CommandError>(__TAURI_INVOKE("list_task_reminders", { taskId })),
	deleteReminder: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("delete_reminder", { id })),
	getTimezone: () => typedError<string, CommandError>(__TAURI_INVOKE("get_timezone")),
	setTimezone: (timezone: string) => typedError<string, CommandError>(__TAURI_INVOKE("set_timezone", { timezone })),
	getModeStatus: () => typedError<ModeStatus, CommandError>(__TAURI_INVOKE("get_mode_status")),
	setRest: (minutes: number | null) => typedError<ModeStatus, CommandError>(__TAURI_INVOKE("set_rest", { minutes })),
	startFocus: (minutes: number, taskId: number | null) => typedError<ModeStatus, CommandError>(__TAURI_INVOKE("start_focus", { minutes, taskId })),
	stopFocus: () => typedError<ModeStatus, CommandError>(__TAURI_INVOKE("stop_focus")),
	getWorkHours: () => typedError<WorkDay[], CommandError>(__TAURI_INVOKE("get_work_hours")),
	setWorkHours: (days: WorkDay[]) => typedError<WorkDay[], CommandError>(__TAURI_INVOKE("set_work_hours", { days })),
	getPrayerSettings: () => typedError<PrayerSettings, CommandError>(__TAURI_INVOKE("get_prayer_settings")),
	setPrayerSettings: (settings: PrayerSettings) => typedError<PrayerSettings, CommandError>(__TAURI_INVOKE("set_prayer_settings", { settings })),
	getPrayerDay: () => typedError<PrayerWindow[], CommandError>(__TAURI_INVOKE("get_prayer_day")),
	getProfile: () => typedError<Profile, CommandError>(__TAURI_INVOKE("get_profile")),
	saveProfile: (profile: Profile) => typedError<Profile, CommandError>(__TAURI_INVOKE("save_profile", { profile })),
	isOnboarded: () => typedError<boolean, CommandError>(__TAURI_INVOKE("is_onboarded")),
	completeOnboarding: () => typedError<null, CommandError>(__TAURI_INVOKE("complete_onboarding")),
	listGoals: () => typedError<Goal[], CommandError>(__TAURI_INVOKE("list_goals")),
	createGoal: (input: GoalInput) => typedError<Goal, CommandError>(__TAURI_INVOKE("create_goal", { input })),
	updateGoal: (id: number, input: GoalInput) => typedError<Goal, CommandError>(__TAURI_INVOKE("update_goal", { id, input })),
	setGoalStatus: (id: number, status: GoalStatus) => typedError<Goal, CommandError>(__TAURI_INVOKE("set_goal_status", { id, status })),
	deleteGoal: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("delete_goal", { id })),
	listMilestones: (goalId: number) => typedError<Milestone[], CommandError>(__TAURI_INVOKE("list_milestones", { goalId })),
	addMilestones: (goalId: number, milestones: MilestoneInput[]) => typedError<Milestone[], CommandError>(__TAURI_INVOKE("add_milestones", { goalId, milestones })),
	setMilestoneStatus: (id: number, status: MilestoneStatus) => typedError<Milestone, CommandError>(__TAURI_INVOKE("set_milestone_status", { id, status })),
	deleteMilestone: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("delete_milestone", { id })),
	proposePlan: (goalId: number) => typedError<PlanProposal, CommandError>(__TAURI_INVOKE("propose_plan", { goalId })),
	listSkills: () => typedError<Skill[], CommandError>(__TAURI_INVOKE("list_skills")),
	createSkill: (name: string) => typedError<Skill, CommandError>(__TAURI_INVOKE("create_skill", { name })),
	deleteSkill: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("delete_skill", { id })),
	getNudgeBudget: () => typedError<number, CommandError>(__TAURI_INVOKE("get_nudge_budget")),
	setNudgeBudget: (perHour: number) => typedError<number, CommandError>(__TAURI_INVOKE("set_nudge_budget", { perHour })),
	listRecentNudges: (limit: number) => typedError<Nudge[], CommandError>(__TAURI_INVOKE("list_recent_nudges", { limit })),
	getHealthOverview: () => typedError<HealthOverview, CommandError>(__TAURI_INVOKE("get_health_overview")),
	setHealthEnabled: (enabled: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_health_enabled", { enabled })),
	logHabit: (kind: HabitKind) => typedError<null, CommandError>(__TAURI_INVOKE("log_habit", { kind })),
	setWaterTarget: (target: number) => typedError<null, CommandError>(__TAURI_INVOKE("set_water_target", { target })),
	addMedicine: (name: string, times: string[]) => typedError<Medicine, CommandError>(__TAURI_INVOKE("add_medicine", { name, times })),
	deleteMedicine: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("delete_medicine", { id })),
	getProgress: () => typedError<ProgressSummary, CommandError>(__TAURI_INVOKE("get_progress")),
	getRewardSound: () => typedError<boolean, CommandError>(__TAURI_INVOKE("get_reward_sound")),
	setRewardSound: (enabled: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_reward_sound", { enabled })),
	getAiStatus: () => typedError<AiStatus, CommandError>(__TAURI_INVOKE("get_ai_status")),
	getAiPresetDefaults: (preset: Preset) => __TAURI_INVOKE<AiSettings>("get_ai_preset_defaults", { preset }),
	saveAiSettings: (settings: AiSettings) => typedError<AiStatus, CommandError>(__TAURI_INVOKE("save_ai_settings", { settings })),
	setAiKey: (key: string) => typedError<AiStatus, CommandError>(__TAURI_INVOKE("set_ai_key", { key })),
	deleteAiKey: () => typedError<AiStatus, CommandError>(__TAURI_INVOKE("delete_ai_key")),
	testAiConnection: () => typedError<null, CommandError>(__TAURI_INVOKE("test_ai_connection")),
	askItqan: (question: string) => typedError<string, CommandError>(__TAURI_INVOKE("ask_itqan", { question })),
	getAutostart: () => typedError<boolean, CommandError>(__TAURI_INVOKE("get_autostart")),
	setAutostart: (enabled: boolean) => typedError<boolean, CommandError>(__TAURI_INVOKE("set_autostart", { enabled })),
	getCoachSettings: () => typedError<CoachSettings, CommandError>(__TAURI_INVOKE("get_coach_settings")),
	setNudgesPaused: (minutes: number | null) => typedError<CoachSettings, CommandError>(__TAURI_INVOKE("set_nudges_paused", { minutes })),
	listModules: () => typedError<ModuleState[], CommandError>(__TAURI_INVOKE("list_modules")),
	setModuleEnabled: (id: string, enabled: boolean) => typedError<ModuleState[], CommandError>(__TAURI_INVOKE("set_module_enabled", { id, enabled })),
	draftBeliefs: (answers: Answer[]) => typedError<DraftBelief[], CommandError>(__TAURI_INVOKE("draft_beliefs", { answers })),
	saveBeliefNotes: (drafts: DraftBelief[]) => typedError<null, CommandError>(__TAURI_INVOKE("save_belief_notes", { drafts })),
	listProposals: () => typedError<Proposal[], CommandError>(__TAURI_INVOKE("list_proposals")),
	acceptProposal: (id: number) => typedError<Proposal[], CommandError>(__TAURI_INVOKE("accept_proposal", { id })),
	rejectProposal: (id: number) => typedError<Proposal[], CommandError>(__TAURI_INVOKE("reject_proposal", { id })),
	openMainWindow: (to: string) => typedError<null, CommandError>(__TAURI_INVOKE("open_main_window", { to })),
};

/** Events */
export const events = {
	goalsChanged: makeEvent<GoalsChanged>("goals-changed"),
	healthChanged: makeEvent<HealthChanged>("health-changed"),
	modeChanged: makeEvent<ModeChanged>("mode-changed"),
	modulesChanged: makeEvent<ModulesChanged>("modules-changed"),
	navigate: makeEvent<Navigate>("navigate"),
	overlayChanged: makeEvent<OverlayChanged>("overlay-changed"),
	overlayCursor: makeEvent<OverlayCursor>("overlay-cursor"),
	proposalsChanged: makeEvent<ProposalsChanged>("proposals-changed"),
	rewardEarned: makeEvent<RewardEarned>("reward-earned"),
	tasksChanged: makeEvent<TasksChanged>("tasks-changed"),
};

/* Types */
export type AgentKind = "coach" | "planner" | "health" | "focusGuardian" | "learning" | "reviewer" | "memory";

export type AiSettings = {
	enabled: boolean,
	preset: Preset,
	baseUrl: string,
	fastModel: string,
	smartModel: string,
	localFallback: boolean,
};

export type AiStatus = {
	settings: AiSettings,
	hasKey: boolean,
	needsKey: boolean,
};

export type Answer = {
	question: string,
	answer: string,
};

export type AppInfo = {
	name: string,
	version: string,
	schemaVersion: number,
};

export type Badge = {
	id: BadgeId,
	title: string,
	description: string,
	earned: boolean,
};

export type BadgeId = "firstShip" | "tenShips" | "firstFocus" | "focusFifty" | "weekStreak" | "monthStreak" | "learner";

export type BeliefKind = "motivator" | "preference" | "pattern" | "constraint" | "goal";

export type Bubble = {
	id: number,
	text: string,
	actions: BubbleAction[],
};

export type BubbleAction = {
	id: string,
	label: string,
};

export type Category = {
	id: number,
	name: string,
	colour: string,
	icon: string,
	builtin: boolean,
};

export type CategoryInput = {
	name: string,
	colour: string,
	icon: string,
};

export type Celebration = "levelUp" | "allDone";

export type CoachSettings = {
	budgetPerHour: number,
	pausedUntil: string | null,
};

export type CoachStyle = "mentor" | "manager" | "trainer";

export type CommandError = {
	message: string,
};

export type DaySummary = {
	date: string,
	xp: number,
	focusMinutes: number,
	active: boolean,
};

export type DraftBelief = {
	statement: string,
	kind: BeliefKind,
	subject: DraftSubject,
	strength: Strength,
};

export type DraftSubject = { type: "motivator"; motivator: Motivator } | { type: "coachStyle"; style: CoachStyle } | { type: "note" };

export type FocusSession = {
	id: number,
	taskId: number | null,
	startedAt: string,
	plannedMinutes: number,
	endedAt: string | null,
	completed: boolean,
};

export type FocusStatus = {
	session: FocusSession,
	progress: number | null,
	endsAt: string,
	pausedForPrayer: boolean,
};

export type FollowMode = "follow" | "corner" | "hidden";

export type Goal = {
	id: number,
	title: string,
	motivator: Motivator | null,
	targetDate: string | null,
	status: GoalStatus,
	createdAt: string,
	completedAt: string | null,
};

export type GoalInput = {
	title: string,
	motivator: Motivator | null,
	targetDate: string | null,
};

export type GoalStatus = "active" | "done" | "archived";

export type GoalsChanged = null;

export type Habit = {
	id: number,
	kind: HabitKind,
	name: string,
	target: number | null,
	enabled: boolean,
};

export type HabitKind = "stretch" | "eyeRest" | "water" | "medicine";

export type HealthChanged = null;

export type HealthOverview = {
	enabled: boolean,
	waterToday: number,
	waterTarget: number,
	stretchesToday: number,
	eyeRestsToday: number,
	medicines: Medicine[],
};

export type HighLatitudeRule = "middleOfTheNight" | "seventhOfTheNight" | "twilightAngle";

export type LevelProgress = {
	level: number,
	xpIntoLevel: number,
	xpForNext: number,
};

export type Madhab = "shafi" | "hanafi";

export type Medicine = {
	habit: Habit,
	reminders: Reminder[],
};

export type Method = "muslimWorldLeague" | "egyptian" | "karachi" | "ummAlQura" | "dubai" | "northAmerica" | "kuwait" | "qatar";

export type Milestone = {
	id: number,
	goalId: number,
	title: string,
	weekStart: string,
	status: MilestoneStatus,
	completedAt: string | null,
};

export type MilestoneInput = {
	title: string,
	weekStart: string,
};

export type MilestoneStatus = "open" | "done";

export type Mode = "work" | "evening" | "rest" | "focus";

export type ModeChanged = ModeStatus;

export type ModeStatus = {
	mode: Mode,
	scheduledMode: Mode,
	restUntil: string | null,
	focus: FocusStatus | null,
	nextPrayer: PrayerWindow | null,
	activePrayer: PrayerWindow | null,
};

export type ModuleState = {
	id: string,
	enabled: boolean,
};

export type ModulesChanged = null;

export type Motivator = "learning" | "building" | "health" | "money" | "recognition" | "family" | "freedom" | "status";

export type MotivatorWeight = {
	motivator: Motivator,
	weight: number,
};

export type Navigate = {
	to: string,
};

export type Nudge = {
	id: number,
	agent: AgentKind,
	kind: string,
	priority: Priority,
	text: string,
	style: string | null,
	mode: string | null,
	firedAt: string,
	outcome: Outcome | null,
	action: string | null,
	outcomeAt: string | null,
};

export type OrbState = "idle" | "happy" | "alert" | "focus" | "resting" | "critical" | "listening" | "evening";

export type Outcome = "accepted" | "snoozed" | "dismissed" | "ignored";

export type OverlayChanged = OverlaySnapshot;

export type OverlayCursor = {
	x: number,
	y: number,
};

export type OverlaySnapshot = {
	orbState: OrbState,
	followMode: FollowMode,
	bubble: Bubble | null,
	progress: number | null,
	panelOpen: boolean,
	docked: boolean,
};

export type PlanProposal = {
	milestones: MilestoneInput[],
	sessionsPerWeek: number,
	sessionMinutes: number,
	firstTask: string,
	source: PlanSource,
	notice: string | null,
};

export type PlanSource = "rules" | "ai";

export type Prayer = "fajr" | "dhuhr" | "jumuah" | "asr" | "maghrib" | "isha";

export type PrayerSettings = {
	enabled: boolean,
	city: string | null,
	latitude: number | null,
	longitude: number | null,
	method: Method,
	madhab: Madhab,
	highLatitudeRule: HighLatitudeRule,
	pauseBeforeMinutes: number,
	pauseAfterMinutes: number,
	jumuahBreak: boolean,
};

export type PrayerWindow = {
	prayer: Prayer,
	at: string,
	pauseFrom: string,
	pauseUntil: string,
};

export type Preset = "groq" | "ollama" | "llamaCpp" | "openAi" | "openRouter" | "custom";

export type Priority = "learningTip" | "rhythm" | "health" | "drift" | "critical";

export type Profile = {
	name: string | null,
	motivators: MotivatorWeight[],
	situation: string | null,
	freeHoursPerWeek: number | null,
	age: number | null,
	coachStyle: CoachStyle,
	familyStartMinute: number | null,
	familyEndMinute: number | null,
	updatedAt: string | null,
};

export type ProgressSummary = {
	totalXp: number,
	level: LevelProgress,
	streak: Streak,
	todayXp: number,
	days: DaySummary[],
	badges: Badge[],
};

export type Proposal = {
	id: number,
	kind: string,
	title: string,
	reason: string,
	effect: string,
	status: ProposalStatus,
	createdAt: string,
	expiresAt: string,
};

export type ProposalStatus = "pending" | "accepted" | "rejected" | "expired";

export type ProposalsChanged = null;

export type QuickAddOutcome = {
	task: Task,
	notice: string | null,
};

export type Rect = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

export type Reminder = {
	id: number,
	taskId: number | null,
	title: string,
	anchorAt: string,
	nextAt: string | null,
	rrule: string | null,
	timezone: string,
	critical: boolean,
	snoozedUntil: string | null,
	lastFiredAt: string | null,
};

export type ReminderInput = {
	taskId: number | null,
	title: string | null,
	at: string,
	rrule: string | null,
	critical: boolean,
};

export type RewardEarned = {
	outcome: RewardOutcome,
	celebration: Celebration | null,
	sound: boolean,
};

export type RewardOutcome = {
	amount: number,
	totalXp: number,
	level: LevelProgress,
	leveledUp: boolean,
	streak: Streak,
};

export type Skill = {
	id: number,
	name: string,
	xp: number,
	level: LevelProgress,
};

export type Streak = {
	current: number,
	best: number,
	freezes: number,
	lastActiveDay: string | null,
};

export type Strength = "low" | "medium" | "high";

export type Task = {
	id: number,
	title: string,
	notes: string | null,
	categoryId: number | null,
	kind: TaskKind,
	priority: number,
	dueAt: string | null,
	isTopThree: boolean,
	status: TaskStatus,
	completedAt: string | null,
	parentId: number | null,
	goalId: number | null,
	skillId: number | null,
	createdAt: string,
	updatedAt: string,
};

export type TaskFilter = {
	status: TaskStatus | null,
	categoryId: number | null,
	dueBefore: string | null,
};

export type TaskInput = {
	title: string,
	notes: string | null,
	categoryId: number | null,
	kind: TaskKind,
	priority: number,
	dueAt: string | null,
	parentId: number | null,
	goalId: number | null,
	skillId: number | null,
};

export type TaskKind = "output" | "learning" | "deepWork" | "habit";

export type TaskStatus = "open" | "done";

export type TasksChanged = null;

export type WorkDay = {
	weekday: number,
	enabled: boolean,
	startMinute: number,
	endMinute: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

