// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getAppInfo: () => typedError<AppInfo, CommandError>(__TAURI_INVOKE("get_app_info")),
	setOverlayHitAreas: (rects: Rect[]) => typedError<null, CommandError>(__TAURI_INVOKE("set_overlay_hit_areas", { rects })),
	getOverlayState: () => typedError<OverlaySnapshot, CommandError>(__TAURI_INVOKE("get_overlay_state")),
	setOrbState: (state: OrbState) => typedError<null, CommandError>(__TAURI_INVOKE("set_orb_state", { state })),
	setFollowMode: (mode: FollowMode) => typedError<null, CommandError>(__TAURI_INVOKE("set_follow_mode", { mode })),
	setOrbProgress: (progress: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("set_orb_progress", { progress })),
	showBubble: (text: string, actions: BubbleAction[]) => typedError<number, CommandError>(__TAURI_INVOKE("show_bubble", { text, actions })),
	resolveBubble: (id: number, actionId: string | null) => typedError<null, CommandError>(__TAURI_INVOKE("resolve_bubble", { id, actionId })),
	setPanelOpen: (open: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_panel_open", { open })),
	listTasks: (filter: TaskFilter) => typedError<Task[], CommandError>(__TAURI_INVOKE("list_tasks", { filter })),
	createTask: (input: TaskInput) => typedError<Task, CommandError>(__TAURI_INVOKE("create_task", { input })),
	updateTask: (id: number, input: TaskInput) => typedError<Task, CommandError>(__TAURI_INVOKE("update_task", { id, input })),
	setTaskStatus: (id: number, status: TaskStatus) => typedError<Task, CommandError>(__TAURI_INVOKE("set_task_status", { id, status })),
	setTaskTopThree: (id: number, on: boolean) => typedError<Task, CommandError>(__TAURI_INVOKE("set_task_top_three", { id, on })),
	deleteTask: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("delete_task", { id })),
	listCategories: () => typedError<Category[], CommandError>(__TAURI_INVOKE("list_categories")),
	createCategory: (input: CategoryInput) => typedError<Category, CommandError>(__TAURI_INVOKE("create_category", { input })),
	quickAddTask: (text: string) => typedError<QuickAddOutcome, CommandError>(__TAURI_INVOKE("quick_add_task", { text })),
	createReminder: (input: ReminderInput) => typedError<Reminder, CommandError>(__TAURI_INVOKE("create_reminder", { input })),
	listTaskReminders: (taskId: number) => typedError<Reminder[], CommandError>(__TAURI_INVOKE("list_task_reminders", { taskId })),
	deleteReminder: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("delete_reminder", { id })),
	getTimezone: () => typedError<string, CommandError>(__TAURI_INVOKE("get_timezone")),
	setTimezone: (timezone: string) => typedError<string, CommandError>(__TAURI_INVOKE("set_timezone", { timezone })),
	getModeStatus: () => typedError<ModeStatus, CommandError>(__TAURI_INVOKE("get_mode_status")),
	setRest: (minutes: number | null) => typedError<ModeStatus, CommandError>(__TAURI_INVOKE("set_rest", { minutes })),
	startFocus: (minutes: number, taskId: number | null) => typedError<ModeStatus, CommandError>(__TAURI_INVOKE("start_focus", { minutes, taskId })),
	stopFocus: () => typedError<ModeStatus, CommandError>(__TAURI_INVOKE("stop_focus")),
	getWorkHours: () => typedError<WorkDay[], CommandError>(__TAURI_INVOKE("get_work_hours")),
	setWorkHours: (days: WorkDay[]) => typedError<WorkDay[], CommandError>(__TAURI_INVOKE("set_work_hours", { days })),
	getPrayerSettings: () => typedError<PrayerSettings, CommandError>(__TAURI_INVOKE("get_prayer_settings")),
	setPrayerSettings: (settings: PrayerSettings) => typedError<PrayerSettings, CommandError>(__TAURI_INVOKE("set_prayer_settings", { settings })),
	getPrayerDay: () => typedError<PrayerWindow[], CommandError>(__TAURI_INVOKE("get_prayer_day")),
	getProfile: () => typedError<Profile, CommandError>(__TAURI_INVOKE("get_profile")),
	saveProfile: (profile: Profile) => typedError<Profile, CommandError>(__TAURI_INVOKE("save_profile", { profile })),
	isOnboarded: () => typedError<boolean, CommandError>(__TAURI_INVOKE("is_onboarded")),
	completeOnboarding: () => typedError<null, CommandError>(__TAURI_INVOKE("complete_onboarding")),
};

/** Events */
export const events = {
	modeChanged: makeEvent<ModeChanged>("mode-changed"),
	overlayChanged: makeEvent<OverlayChanged>("overlay-changed"),
	overlayCursor: makeEvent<OverlayCursor>("overlay-cursor"),
	tasksChanged: makeEvent<TasksChanged>("tasks-changed"),
};

/* Types */
export type AppInfo = {
	name: string,
	version: string,
	schemaVersion: number,
};

export type Bubble = {
	id: number,
	text: string,
	actions: BubbleAction[],
};

export type BubbleAction = {
	id: string,
	label: string,
};

export type Category = {
	id: number,
	name: string,
	colour: string,
	icon: string,
	builtin: boolean,
};

export type CategoryInput = {
	name: string,
	colour: string,
	icon: string,
};

export type CoachStyle = "mentor" | "manager" | "trainer";

export type CommandError = {
	message: string,
};

export type FocusSession = {
	id: number,
	taskId: number | null,
	startedAt: string,
	plannedMinutes: number,
	endedAt: string | null,
	completed: boolean,
};

export type FocusStatus = {
	session: FocusSession,
	progress: number | null,
	endsAt: string,
	pausedForPrayer: boolean,
};

export type FollowMode = "follow" | "corner" | "hidden";

export type HighLatitudeRule = "middleOfTheNight" | "seventhOfTheNight" | "twilightAngle";

export type Madhab = "shafi" | "hanafi";

export type Method = "muslimWorldLeague" | "egyptian" | "karachi" | "ummAlQura" | "dubai" | "northAmerica" | "kuwait" | "qatar";

export type Mode = "work" | "evening" | "rest" | "focus";

export type ModeChanged = ModeStatus;

export type ModeStatus = {
	mode: Mode,
	scheduledMode: Mode,
	restUntil: string | null,
	focus: FocusStatus | null,
	nextPrayer: PrayerWindow | null,
	activePrayer: PrayerWindow | null,
};

export type Motivator = "learning" | "building" | "health" | "money" | "recognition" | "family" | "freedom" | "status";

export type MotivatorWeight = {
	motivator: Motivator,
	weight: number,
};

export type OrbState = "idle" | "happy" | "alert" | "focus" | "resting" | "critical" | "listening" | "evening";

export type OverlayChanged = OverlaySnapshot;

export type OverlayCursor = {
	x: number,
	y: number,
};

export type OverlaySnapshot = {
	orbState: OrbState,
	followMode: FollowMode,
	bubble: Bubble | null,
	progress: number | null,
	panelOpen: boolean,
	docked: boolean,
};

export type Prayer = "fajr" | "dhuhr" | "jumuah" | "asr" | "maghrib" | "isha";

export type PrayerSettings = {
	enabled: boolean,
	city: string | null,
	latitude: number | null,
	longitude: number | null,
	method: Method,
	madhab: Madhab,
	highLatitudeRule: HighLatitudeRule,
	pauseBeforeMinutes: number,
	pauseAfterMinutes: number,
	jumuahBreak: boolean,
};

export type PrayerWindow = {
	prayer: Prayer,
	at: string,
	pauseFrom: string,
	pauseUntil: string,
};

export type Profile = {
	name: string | null,
	motivators: MotivatorWeight[],
	situation: string | null,
	freeHoursPerWeek: number | null,
	age: number | null,
	coachStyle: CoachStyle,
	familyStartMinute: number | null,
	familyEndMinute: number | null,
	updatedAt: string | null,
};

export type QuickAddOutcome = {
	task: Task,
	notice: string | null,
};

export type Rect = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

export type Reminder = {
	id: number,
	taskId: number | null,
	title: string,
	anchorAt: string,
	nextAt: string | null,
	rrule: string | null,
	timezone: string,
	critical: boolean,
	snoozedUntil: string | null,
	lastFiredAt: string | null,
};

export type ReminderInput = {
	taskId: number | null,
	title: string | null,
	at: string,
	rrule: string | null,
	critical: boolean,
};

export type Task = {
	id: number,
	title: string,
	notes: string | null,
	categoryId: number | null,
	kind: TaskKind,
	priority: number,
	dueAt: string | null,
	isTopThree: boolean,
	status: TaskStatus,
	completedAt: string | null,
	parentId: number | null,
	createdAt: string,
	updatedAt: string,
};

export type TaskFilter = {
	status: TaskStatus | null,
	categoryId: number | null,
	dueBefore: string | null,
};

export type TaskInput = {
	title: string,
	notes: string | null,
	categoryId: number | null,
	kind: TaskKind,
	priority: number,
	dueAt: string | null,
	parentId: number | null,
};

export type TaskKind = "output" | "learning" | "deepWork" | "habit";

export type TaskStatus = "open" | "done";

export type TasksChanged = null;

export type WorkDay = {
	weekday: number,
	enabled: boolean,
	startMinute: number,
	endMinute: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

